
skillMetadata:
  sections:
    - name: TVHeadend server details
      fields:
        - name: servername
          type: text
          label: TVHeadend server name or IP address
          value: ""
        - name: username
          type: text
          label: Admin or User name
          value: ""
        - name: password
          type: text
          label: Password
          value: ""
    - name: Channel alias
      fields:
        - name: name1
          type: text
          label: Official channel name
          value: ""
        - name: alias1
          type: text
          label: Channel alias
          value: ""
    - name: Channel alias
      fields:
        - name: name2
          type: text
          label: Official channel name
          value: ""
        - name: alias2
          type: text
          label: Channel alias
          value: ""
    - name: Channel alias
      fields:
        - name: name3
          type: text
          label: Official channel name
          value: ""
        - name: alias3
          type: text
          label: Channel alias
          value: ""
    - name: Channel alias
      fields:
        - name: name4
          type: text
          label: Official channel name
          value: ""
        - name: alias4
          type: text
          label: Channel alias
          value: ""
    - name: Channel alias
      fields:
        - name: name5
          type: text
          label: Official channel name
          value: ""
        - name: alias1
          type: text
          label: Channel alias
          value: ""
